# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Lalit Kumar
title: Senior Software Engineer
email: lk.iitkgp@gmail.com
website: https://lkiitkgp.github.io/me/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  lkiitkgp
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: lalit.nhr
# flickr_username: jekyll
instagram_username: lalit.nhr
linkedin_username: lalitkgp
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Lalit and I'm a senior software engineer. I have 2 years+ experience in making softwares. I have worked at two companies gaining technical, teamwork, and leadership skills.<br>

  *I am most skilled in:*  <mark>Node.js</mark>  and  <mark>DevOps</mark><br><br>
  
  <b>Frameworks:</b>  <mark>Express</mark>   <mark>Django</mark>     <b>Databases:</b>  <mark>MongoDB</mark>   <mark>MSSQL</mark><br>

  <b>Programming Languages:</b>  <mark>JavaScript</mark>   <mark>Java</mark>   <mark>Python</mark>   <mark>Groovy</mark><br>
  
  <b>Softwares & CI/CD Tools:</b>  <mark>Docker</mark>   <mark>Jenkins</mark>   <mark>Azure</mark>   <mark>Gitlab</mark>   <mark>BitBucket</mark>   <mark>GitHub Actions</mark>   <mark>Jira</mark>   <mark>AWS</mark>


content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: HCL Technoligies Ltd
        link: plugins.hcltechsw.com
        # link_text: boringcompany.com
        sub_title: Senior Software Engineer
        caption: September 2020 - Present
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
      - layout: left
        title: Perpule, Bangalore
        link: blog.perpule.com
        # link_text: boringcompany.com
        sub_title: Software Development Intern
        caption: May 2019 - July 2019
        # quote: >
        #   Developing AmazonPay, Paytm Auto Debit, PhonePe and Paytm UPI using core J2EE Patterns, for Auto Payment flow
        description: | # this will include new lines to allow paragraphs
          Developed payment microservice, using Rest APIs, Cloud SQL, Google App Engine. Reducing transaction latency by 83%<br>
          Responsible for adding new payment methods, code-refactoring, optimizations adhering to the testing, delivering to the production team

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Indian Institue of Technology, Kharagpur
        caption: CGPA 7.33 <br> 2015 - 2020
        sub_title: B.Tech. + M.Tech.
        quote: >
          Established in 1951, the institute is the first of the IITs to be established and is recognised as an Institute of National Importance. In 2019 it was awarded the status of Institute of Eminence by the Government of India
        description: | # this will include new lines to allow paragraphs
          <b>Master’s Thesis Dissertation:</b> Propeller Characteristics Generation Software<br>
            Objective: *Develope software for generating open water characteristics of BSeries ship propeller using python*
          
          <b>Bachelor’s Thesis Dissertation:</b> Data Analytics for Condition-based Maintenance<br>
            Objective: *Improving condition-based maintenance of the Combined Diesel electric and Gas propulsion plant of a naval vessel using various data analytics and machine learning approaches*

          I spent a lot of my free time as a student senate member of the *IIT Kharagpur* taking on roles such as *Hall President* and *General Secretary*

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interest in software engineering some of my other interests and hobbies are:
      - Cooking
      - Playing Chess
      - Lifting weights in JIM

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
